# TrfmconfigM2.yaml

## Where the samples will be written
save_data: ./Vocab/example
## Where the vocab(s) will be written
src_vocab: ./Vocab/example/example.vocab.src
tgt_vocab: ./Vocab/example/example.vocab.tgt
# Prevent overwriting existing files in the folder
overwrite: False

# Corpus opts:
data:
    corpus_1:
        path_src: ./token(-CF2-)/train_m2_src.txt
        path_tgt: ./token(-CF2-)/train_m2_tgt.txt
    corpus_2:
        path_src: ./token(-CF2H)/train_m2_src.txt
        path_tgt: ./token(-CF2H)/train_m2_tgt.txt
    corpus_3:
        path_src: ./token(-CF3)/train_m2_src.txt
        path_tgt: ./token(-CF3)/train_m2_tgt.txt
    corpus_4:
        path_src: ./token(-CFH-)/train_m2_src.txt
        path_tgt: ./token(-CFH-)/train_m2_tgt.txt
    corpus_5:
        path_src: ./token(-CFH2)/train_m2_src.txt
        path_tgt: ./token(-CFH2)/train_m2_tgt.txt
    corpus_6:
        path_src: ./token(-F)/train_m2_src.txt
        path_tgt: ./token(-F)/train_m2_tgt.txt
    corpus_7:
        path_src: ./token(-OCF2H)/train_m2_src.txt
        path_tgt: ./token(-OCF2H)/train_m2_tgt.txt
    corpus_8:
        path_src: ./token(-OCF3)/train_m2_src.txt
        path_tgt: ./token(-OCF3)/train_m2_tgt.txt
    corpus_9:
        path_src: ./token(-SCF2H)/train_m2_src.txt
        path_tgt: ./token(-SCF2H)/train_m2_tgt.txt
    corpus_10:
        path_src: ./token(-SCF3)/train_m2_src.txt
        path_tgt: ./token(-SCF3)/train_m2_tgt.txt
    valid:
        path_src: ./token/valid_m2_src.txt
        path_tgt: ./token/valid_m2_tgt.txt
# TrfmconfigM2.yaml

save_model: ./M2Trfm_directory/model
log_file: ./M2Trfm_directory/train.log
save_checkpoint_steps: 10000
keep_checkpoint: 10
seed: 42     #seed:123, 456
train_steps: 100000
valid_steps: 10000
report_every: 100
# Stop training if it does not imporve after n validations
early_stopping: 4
warmup_steps: 4000

decoder_type: transformer
encoder_type: transformer
word_vec_size: 256
hidden_size: 256
layers: 6
transformer_ff: 2048
heads: 8

accum_count: 8
optim: adam
adam_beta1: 0.9
adam_beta2: 0.998
decay_method: noam
learning_rate: 2.0
max_grad_norm: 1.0

batch_size: 1024
batch_type: tokens
normalization: tokens
dropout: 0.1
label_smoothing: 0.1

param_init: 0.0
param_init_glorot: 'true'
position_encoding: 'true'

world_size: 1
gpu_ranks:
- 0





